name: portfolio
description: "Howard's portfolio."

publish_to: "none"

version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  animated_theme_switcher: ^2.0.10
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  animated_number_switcher: ^0.0.4
  collection: ^1.19.1
  path: ^1.9.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
